# Errores numéricos: Notas y códigos.

Las computadoras tienen límites, estas no pueden guardar números con una cantidad infinita de dígitos, por lo que existe un límite para el número mas grande y el más pequeño que Python puede guardar en la memoria. El tamaño depende de con qué tipo de dato numérico estemos trabajando.
* float(): Los valores positivos y negativos de una variable tipo flotante, están entre [$10^{308}$,$-10^{308}$]
* complex(): Los valores positivos y negativos de las partes real e imaginaria de una variable compleja, están entre [$10^{308}$,$-10^{308}$], pero no pueden haber valores más grandes que esos. 
Notemos que podemos reescribir un numeros flotantes, utilizando notación científica:
* 2e9 = 2x10^{9} y 1.602e-19 = 1.602x10^{-19}

Si una variable float() excede los límites de tamaño, esta se habrá sobrepasado. Pero, si tenemos una variable float() cuyo valor x<$10^{38}$ y realizamos una operación con dicha variable cuyo resultado exceda los límites de tamaño, por decir $y=x*100$ el resultado no será computado por Python y como resultado aparecerá $y=inf$, es decir, un valor no definido (dentro de los limites computacionales.)

También existe un límite para la magnitud más pequeña con la que puede trabajar python(que puede ser representada por una variable float()), la cual es del orden de $10^{-38}$. Análogamente, si trabajas con una variable float() con un valor mucho más pequeño que dicho orden de magnitud, tu variable está no podrá ser imprimieda por el intérprete de manera adecuada e imprimirá el valor de 0.

Para las variables con valor de número entero: int(), no existe límite alguno para el valor más grande (positivo o negativo). Aquí la cantidad de digitos que guarde Python para una variable que tenga un valor int(), depende enteramente de la capacidad de memoria de la computadora. 

In [7]:
#Ejemplo: Factorial de un número.
def fact(n):
    if n==1:
        return n
    elif n==0:
        return 1
    else:
        return n * fact(n-1)

In [8]:
n=int(input('Dame un numero: '))
print(fact(n))

Dame un numero:  200


788657867364790503552363213932185062295135977687173263294742533244359449963403342920304284011984623904177212138919638830257642790242637105061926624952829931113462857270763317237396988943922445621451664240254033291864131227428294853277524242407573903240321257405579568660226031904170324062351700858796178922222789623703897374720000000000000000000000000000000000000000000000000


In [11]:
n=float(input('Dame un numero: '))
print(fact(n))

Dame un numero:  200


inf


Notamos que para el factorial de int(200), Python no impone límites por sí mismo de la magnitud del valor de fact(200), es decir, solo si el valor numérico de fact() excede la memoria de la computadora, no imprimirá un valor tipo 'inf' y mientras que para float(200), Python imprimió un valor 'inf', pues $fact(200)>10^{38}$

Para variables tipo float() Python los representa con una precisión numérica de 16-dígitos significativos. Cualquier variable float() que sobre pase los 16 dígitos significativos, será cortada a los 16 dígitos. Esto se puede notar con el valor de $\pi$ en Python. $\pi$ es un número irracional, lo que significa que tiene un número infinito de dígitos después del punto decimal, pero Python solo muestra 16 de esos dígitos.
Al nosotros, restamos al valor real de $\pi$ (con una cantidad infinita de dígitos), el valor de Python de $\pi$, obtenemos el $\textbf{error de redondeo}$ el cual es la diferencia entre el valor real, aritmético de un número (en este caso) y el valor numérico de un número con precisión finita (16 dígitos).

Supongamos que tenemos dos números, por decir $x_1=2.2$ y $x_2=2.19999999999999$, técnicamente 'deberían' ser el mismo numero pues si redondeamos $x_2$, pues técnicamente es $x_1$, ¿no?. Verifiquemos en Python.

In [ ]:
x1=2.2
x2=2.1999999999999
print(x1==x2)#esto nos dirá si el x1 es igual a x2 (True) o no (False.)

if x2==x1:
    print(x1)
else:
    print("Nop.")

¿Qué pasó ahí? Si en teoría los dos números con casi iguales, porque eventualmente, podemos suponer que $x_2 \to x_1$ si $x_2 \to \infty$, ¿no? .Pues en realidad, Python es muy cortante. Mientras los dos números sean exactamente los mismos, dígito por dígito, y evaluar si son iguales mediante una condición lógica, pues será falso que $x_1=x_2$. ¿Qué podemos hacer, entonces?

Lo que podemos hacer es calcular la diferencia en valor absoluto de ambos números y poner un criterio. Este criterio, será que si la diferencia en valor absoluto sea menor que una $\epsilon$, la cual representará el orden de magnitud que querramos, entonces, podemos considerar que $x_1=x_2$. En otras palabras, si la diferencia en valor absoluto es aún más pequeña que la épsilon que impongamos, entonces, podemos considerar $x_1=x_2$.

In [37]:
x2=2.199999999999
epsilon= 1e-9
print(float(abs(x2-2.2)))
if abs(x2-2.2)<epsilon:
    print(x2)
else:
    print('Nop.')

1.000088900582341e-12
2.199999999999


A $\epsilon$, se le conoce como el $\textbf{error de redondeo}$ el cual se define como el número que se le tendría que añadir al valor calculado por la computadora para obtener el valor exacto. Por ejemplo, nosotros al importar el valor de $x=\sqrt{2}$ de la librería de Python, obtenemos $x+\epsilon = \sqrt{2}$ donde $\epsilon$ es el error de redondeo y para obtener el valor exacto de $\sqrt{2}$ despejamos x de la ecuación y obtenemos $x=\sqrt{2}-\epsilon$. Sabemos que $\epsilon$ puede ser positivo o negativo, dependiendo de cómo se redondeó la variable x. En general, si la variable numérica x es del orden de 16 dígitos, entonces $\epsilon$ deberá ser del orden aproximado de $\frac{x}{10^{16}}$

Podemos asumir que $\epsilon$ es un número aleatorio con una desviación estandar dada por $\sigma=Cx$ donde $C\approx 10^{-16}$ y se le conoce como la constante de error. Entonces, cuando se presenta el error de redondeo de un número x, se tiene que $\epsilon=\sigma$.

Ahora, ¿qué pasa si sumamos o multiplicamos dos números cada uno con un error de redondeo?, es decir, si tenemos $x_1$ y $x_2$ cada uno con sus respectivas $\sigma_1$ y $\sigma_2$.

* Si sumamos o restamos $x_1$ y $x_2$ con $\sigma_1$ y $\sigma_2$, tenemos que la suma está dada por: $x=x_1+x_2$ y $\sigma^2=\sigma_1^2+\sigma_2^2$, por lo que el error es igual a $\sigma=\sqrt{\sigma_1^2+\sigma_2^2}$. Si $\sigma_1=C*x_1$ y $\sigma_2=C*x_2$, la desviación estandar queda en términos de $x_1$ y $x_2$ como: $\sigma=C\sqrt{x_1^2+x_2^2}$

* Si multiplicamos o dividimos $x_1$ y $x_2$ con $\sigma_1$ y $\sigma_2$, tenemos que la multiplicación y división están dadas por $x=x_1*x_2$ y $x=\frac{x_1}{x_2}$la desviación estándar está dada por: $\frac{\sigma^2}{x^2}=\frac{\sigma_1^2}{x_1^2}+\frac{\sigma_2^2}{x_2^2}$. En términos de $x_1$ y $x_2$, la desviacón estandar está dada como: $\sigma=\sqrt{2}Cx$

Para n números $x_i, i={1,2,3,......,N}$ con sus respectivas desviaciones estándar $\sigma_i=Cx_i, i={1,2,3,......,N}$ tenemos que las sumas y productos están dados por:
* Suma o resta: $\sigma^2=\sum_{i=1}^N \sigma_i^2=\sum_{i=1}^N C^2x_i^2=C^2N\overline{x^2}$ y despejando, queda como: $\sigma=C\sqrt{N}\sqrt{\overline{x^2}}$

Notemos que al sumar más y más números, el valor de $\sigma$ aumenta, es decir, el error va aumentando.

También es útil definir el error fraccional para la suma finita de valores con desviaciones estándar. Esta la definimos como la división de la desviación estandar total sobre el valor de la suma: 
$$
\frac{\sigma}{\sum_{i=1}x_i}=\frac{C}{\sqrt{N}}\frac{\sqrt{\overline{x^2}}}{\overline{x}}
$$
Y el error fraccional para la suma finita disminuye conforme el número de términos va aumentando. ¡Es mejor! ¿Lo es?

El problema viene cuando se substraen números de los cuales uno de ellos sobrepasa el límite de 16 cifras significativas. Python trunca el número y en vez de dar un error fraccional adecuado, en realidad este aumenta.

Consideramos $x=1$ y $y=1+1e^{-14}\sqrt{2}$, los restamos y obtenemos:
$$
y-x=1+1e^{-14}\sqrt{2}-1=1e^{-14}\sqrt{2}
$$
De donde despejamos el valor de $\sqrt{2}$ e intentamos obtener una aproximación del mismo.
$$
\sqrt{2}=1e^{14}(y-x)
$$

## Ejemplo 4.1: Diferencia de dos números.

In [40]:
# Ejemplo 4.1: Diferencia de dos números.

from math import sqrt
x=1
y=1+1e-14*sqrt(2)
print((1e14)*(y-x))
print(sqrt(2))
print(abs(((1e14)*(y-x))-sqrt(2)))

1.4210854715202004
1.4142135623730951
0.006871909147105226


## Ejercicio 4.2: Ecuación cuadrática.

In [68]:
import math
def raices1(a,b,c):
    dis=b*b-4*a*c
    val_raiz=math.sqrt(abs(dis))
    if dis>0:
        print('Raíces reales y de valores distintos.')
        print((-b+val_raiz)/(2*a))
        print((-b-val_raiz)/(2*a))
    elif dis==0:
        print('Solo una raiz real.')
        print(-b/(2*a))
    else:
        print('Raíces complejas.')
        print(-b/2*a,"+i",val_raiz)
        print(-b/2*a,"-i",val_raiz)

In [71]:
a=float(input('Dame el valor de a: '))
b=float(input('Dame el valor de b: '))
c=float(input('Dame el valor de c: '))
if a==0:
    print('No es valido.')
else:
    raices1(a,b,c)

Dame el valor de a:  0.001
Dame el valor de b:  1000
Dame el valor de c:  0.001


Raíces reales y de valores distintos.
-9.999894245993346e-07
-999999.999999


In [70]:
import math
def raices2(a,b,c):
    dis=b*b-4*a*c
    val_raiz=math.sqrt(abs(dis))
    if dis>0:
        print('Raíces reales y de valores distintos.')
        print((2*c)/(-b-val_raiz))
        print((2*c)/(-b+val_raiz))
    elif dis==0:
        print('Solo una raiz real.')
        print((2*c)/(-b))
    else:
        print('Raíces complejas.')
        print(-b/2*a,"+i",val_raiz)
        print(-b/2*a,"-i",val_raiz)

In [72]:
a=float(input('Dame el valor de a: '))
b=float(input('Dame el valor de b: '))
c=float(input('Dame el valor de c: '))
if a==0:
    print('No es valido.')
else:
    raices2(a,b,c)

Dame el valor de a:  0.001
Dame el valor de b:  1000
Dame el valor de c:  0.001


Raíces reales y de valores distintos.
-1.000000000001e-06
-1000010.5755125057


Notamos que las raíces para la ecuación $0.001x^2+1000x+0.001=0$, son distintos para las dos manera propuestas de solución, esto creo yo, es debido al cambio del signo

In [86]:
from numpy import sqrt


def cuadratica(a, b, c):
    """
    Imprime las dos soluciones de la ecuación cuadrática asociada, utilizando 
    las dos formas de la fomula cuadrática para obtener las raíces.
    :constante a: termino cuadrático
    :constante b: termino lineal
    :constante c: termino constante
    """

    print('Primera solución (metodo 1): ', (-b + sqrt(b ** 2 - 4 * a * c)) / (2 * a))
    print('Segunda solución (metodo 1): ', (-b - sqrt(b ** 2 - 4 * a * c)) / (2 * a))
    print('Primera solución (metodo 2): ', (2 * c) / (-b - sqrt(b ** 2 - 4 * a * c)))
    print('Segunda solución (metodo 2): ', (2 * c) / (-b + sqrt(b ** 2 - 4 * a * c)))


cuadratica(0.001, 1000, 0.001)


def raices_cuadraticas(a, b, c):
    """
    Regresa las raíces de una ecuación cuadrática en orden de magnitud ascendente.
    La variación en las soluciones de las dos funciones, se debe a los valores de -b y al discriminante b**2 - 4*a*c.
    Por lo que debemos escoger el método correto para resolver la ecuación en base a que se evite la diferencia de dos números casi iguales.
    Es decir, debemos imponer una tolerancia para que apartir de esa, escoja el metodo que mejor convenga para resolver la ecuación.
    :constante a: termino cuadrático
    :constante b: termino lineal
    :constante c: termino constante
    """
    t = 10*-3
    d = sqrt(b ** 2 - 4 * a * c)
    if abs(d+ b) < t:
        return (2 * c) / (-b + d), (-b + d) / (2 * a),'Primer método.'
    else:
        return (-b - d) / (2 * a), (2 * c) / (-b - d),'Segundo método.'


print(raices_cuadraticas(0.001, 1000, 0.001))

Primera solución (metodo 1):  -9.999894245993346e-07
Segunda solución (metodo 1):  -999999.999999
Primera solución (metodo 2):  -1.000000000001e-06
Segunda solución (metodo 2):  -1000010.5755125057
(-999999.999999, -1.000000000001e-06, 'Segundo método.')


## Ejercicio 4.3

Usando la definición de derivada:
$$
f'(x)=\lim_{\delta \to 0} \frac{f(x+\delta)-f(x)}{\delta}\approx \frac{f(x+\delta)-f(x)}{\delta}
$$
con delta ->0
La computadora no hace el límite de delta -> 0, pero podemos aproximar a un valor lo más razonablemente pequeño.

Para $f(x)=x(x-1)=x^2-x$, tenemos que la derivada es igual a:
$$
f'(x)\approx \frac{(x+\delta)^2-(x+\delta)-(x^2+x)}{\delta}
$$

In [74]:
def derivada(x,delta):
    der=((x+delta)**2-(x+delta)-x**2+x)/delta
    return der

In [75]:
x=1
d=1e-2
print(derivada(x,d))

1.0099999999999998


Para la función $f(x)=x^2-x$, la derivada analítica es igual a: $f(x)=2x-1$ que al ser evaluada en $x=1$, tenemos que:
$$
f'(x=1)=2(1)-1=1
$$
Por lo que los valores de las derivadas analíticas y numéricas no son lo mismo. Saquemos el error absoluto entre ambos resultados.

In [76]:
x=1
d=1e-2
print(abs(derivada(x,d)-1))

0.009999999999999787


Para distintos valores de $\delta={1e-2,1e-4,1e-6,1e-8,1e-10,1e-12,1e-14}$, calculemos los valores de las derivadas junto con sus errores abosultos respecto al valor de la derivada analítica.

In [81]:
x=1
A=[1e-2,1e-4,1e-6,1e-8,1e-10,1e-12,1e-14,1e-16]
for i in A:
    print(i,"\t",derivada(x,i),"\t",abs(derivada(x,i)-1))

0.01 	 1.0099999999999998 	 0.009999999999999787
0.0001 	 1.0000999999992821 	 9.999999928211878e-05
1e-06 	 1.000001000006634 	 1.0000066339443947e-06
1e-08 	 0.999999993922529 	 6.07747097092215e-09
1e-10 	 1.000000082740371 	 8.274037099909037e-08
1e-12 	 1.000088900582341 	 8.890058234101161e-05
1e-14 	 0.9992007221626409 	 0.0007992778373591136
1e-16 	 0.0 	 1.0


Para deltas más y más pequeñas, la aproximación del límite va mejorando, pero en algún punto, empeora debido al error numérico que surge de la diferencia de números que son casi iguales.

## Ejemplo 4.2: Oscilador armónico cuántico a una temperatura finita.

El oscilador armónico cuántico tiene niveles energéticos dados por:
$$
E_n=\hbar \omega(n+\frac{1}{2})
$$
Y sabemos que la energía promedio a una temperatura T está dada por:
$$
<E>=\frac{1}{Z}\sum_{n=0}^{\infty}E_ne^{-\beta E_n}
$$
Con $\beta=\frac{1}{k_BT}$ y $Z=\sum_{n=0}^{\infty}e^{-\beta E_n}$

In [88]:
from math import *
import time

start_time = time.time()

S=0.0
Z=0.0
terminos=10
for n in range(terminos):
    beta=1/100
    E=n+0.5 #niveles energeticos
    S+=exp(-beta*(n+0.5))*(n+0.5)
    Z+=exp(-beta*(n+0.5))
print(S/Z)

print("--- %s segundos ---" % (time.time()  -  start_time))

4.917513884193951
--- 0.0002887248992919922 segundos ---


## Ejemplo 4.3: Multiplicación de matrices.

In [102]:
from numpy import zeros,ones
start_time = time.time()
N=75
C=zeros([N,N],float)
A=ones([N,N],float)
B=ones([N,N],float)
for i in range(N):
    for j in range(N):
        for k in range(N):
            C[i,j]+=A[i,k]*B[k,j]
print(C)
print("--- %s segundos ---" % (time.time()  -  start_time))

[[75. 75. 75. ... 75. 75. 75.]
 [75. 75. 75. ... 75. 75. 75.]
 [75. 75. 75. ... 75. 75. 75.]
 ...
 [75. 75. 75. ... 75. 75. 75.]
 [75. 75. 75. ... 75. 75. 75.]
 [75. 75. 75. ... 75. 75. 75.]]
--- 0.3161313533782959 segundos ---


## Ejercicio 4.4: Integrales.

La integral a calcular es igual a: $\int_{-1}^{1} \sqrt{1-x^2}dx=\frac{\pi}{2}$ y tenemos que podemos aproximar el valor de la integral a:
$$
I=\int_{-1}^{1} \sqrt{1-x^2}dx=\lim_{N \to \infty}\sum_{k=1}^{N}hy_k\approx \sum_{k=1}^{N}\frac{2}{N}\sqrt{1-({-1+\frac{2}{N}k})^2}
$$

In [99]:
from numpy import linspace, sqrt
import time
start_time = time.time()
from math import pi
N = 100
h = 2/N
x = linspace(-1,1,N)
y = sqrt(1 - x**2)

I = h*sum(y)
delta = I - pi
print('EL valor de la integral es igual a = {}'.format(I))
print('delta = {}'.format(delta))
print("--- %s segundos ---" % (time.time()  -  start_time))

EL valor de la integral es igual a = 1.553417929404895
delta = -1.588174724184898
--- 0.0008647441864013672 segundos ---


In [104]:
from numpy import linspace, sqrt
from math import pi
import time
start_time = time.time()
v=[10,100,1000,10000,100000,1000000]
for i in v:
    h = 2/i
    x = linspace(-1,1,i)
    y = sqrt(1 - x**2)
    I = h*sum(y)
    print(I,"--- %s segundos ---" % (time.time()  -  start_time))

1.3586543247679108 --- 0.00031495094299316406 segundos ---
1.553417929404895 --- 0.0007176399230957031 segundos ---
1.5691729158636196 --- 0.0013306140899658203 segundos ---
1.5706375839994526 --- 0.0031642913818359375 segundos ---
1.5707805662399095 --- 0.01906585693359375 segundos ---
1.5707947543354452 --- 0.17108678817749023 segundos ---
